version: "3.8"

services:
  web-dev:
    build: ./backend
    container_name: backend-web-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend/
    ports:
      - "1337:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db-dev
  db-dev:
    restart: always
    image: postgres:15
    container_name: backend-postgres-dev
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend_dev
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data/ 

  pgadmin-dev:
    image: dpage/pgadmin4
    container_name: backend-pgadmin-dev
    depends_on:
      - db-dev
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always

volumes:
  postgres-dev-data: