# Generated by Django 3.2.25 on 2024-06-04 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the restaurant.', max_length=255)),
                ('user', models.OneToOneField(help_text='The user managing this restaurant.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the zone.', max_length=255)),
                ('bookable', models.BooleanField(default=False, help_text='Indicates if the zone is bookable.')),
                ('restaurant', models.ForeignKey(help_text='The restaurant this zone belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='The start date and time of the vacation.')),
                ('end', models.DateTimeField(help_text='The end date and time of the vacation.')),
                ('restaurant', models.ForeignKey(help_text='The restaurant this vacation belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(help_text='The number of seats at the table.')),
                ('bookable', models.BooleanField(default=False, help_text='Indicates if the table is bookable.')),
                ('combinable', models.BooleanField(default=False, help_text='Indicates if the table can be combined with others.')),
                ('zone', models.ForeignKey(help_text='The zone this table belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.zone')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], help_text='The day of the week.', max_length=2)),
                ('open', models.TimeField(help_text='The opening time for bookings.')),
                ('close', models.TimeField(help_text='The closing time for bookings.')),
                ('default_duration', models.TimeField(help_text='The default duration for bookings.')),
                ('restaurant', models.ForeignKey(help_text='The restaurant this booking period belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
