# Generated by Django 3.2.25 on 2024-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='availability',
            field=models.JSONField(default=dict, help_text='Availability of the table.'),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(help_text='The name of the table.', max_length=255, null=True),
        ),
    ]
