# Generated by Django 3.2.25 on 2024-06-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='The name of the restaurant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(help_text='The user managing this restaurant.', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='table',
            name='bookable',
            field=models.BooleanField(default=False, help_text='Indicates if the table is bookable.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(help_text='The number of seats at the table.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='combinable',
            field=models.BooleanField(default=False, help_text='Indicates if the table can be combined with others.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(help_text='The zone this table belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.zone'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end',
            field=models.DateTimeField(help_text='The end date and time of the vacation.'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this vacation belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start',
            field=models.DateTimeField(help_text='The start date and time of the vacation.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='bookable',
            field=models.BooleanField(default=False, help_text='Indicates if the zone is bookable.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(help_text='The name of the zone.', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this zone belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], help_text='The day of the week.', max_length=2)),
                ('open', models.TimeField(help_text='The opening time for bookings.')),
                ('close', models.TimeField(help_text='The closing time for bookings.')),
                ('default_duration', models.TimeField(help_text='The default duration for bookings.')),
                ('restaurant', models.ForeignKey(help_text='The restaurant this booking period belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
