# Generated by Django 3.2.25 on 2024-06-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20240610_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='availability',
        ),
    ]
