# Generated by Django 3.2.25 on 2024-06-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_table_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBookingDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(help_text='The default duration for bookings.')),
            ],
        ),
    ]
