# Generated by Django 3.2.25 on 2024-06-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_defaultbookingduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingperiod',
            name='default_duration',
        ),
    ]
