# Generated by Django 3.2.25 on 2024-06-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_bookingperiod_default_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultbookingduration',
            name='restaurant',
            field=models.ForeignKey(default='', help_text='The restaurant this zone belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
