# Generated by Django 3.2.25 on 2024-06-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_defaultbookingduration_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this vacation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='restaurant.restaurant'),
        ),
    ]
