# Generated by Django 3.2.25 on 2024-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_vacation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end',
            field=models.DateField(help_text='The end date and time of the vacation.'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start',
            field=models.DateField(help_text='The start date and time of the vacation.'),
        ),
    ]
