upstream web {
    server web:8000;
}

server {
    listen 8080;
    server_name proxy;

    location / {
        proxy_pass http://web;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /backend/staticfiles/;
    }

    location /.well-known/acme-challenge/ {
        root /backend/staticfiles;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /.well-known/acme-challenge/ {
        root /backend/staticfiles;
    }

#    location / {
#        return 301 https://$host$request_uri;
#    }

    return 301 https://$host$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 443 ssl; 

    root /your/project/root/public/directory/path;
    index index.html index.php index.htm index.nginx-debian.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    server_name example.com;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    error_page 404 /index.php;

    location / { 
        try_files $uri $uri/ /index.php?$query_string;
    }
}
