# Generated by Django 3.2.25 on 2024-06-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='The name of the guest.', max_length=255)),
                ('guest_phone', models.CharField(help_text='The phone number of the guest.', max_length=20)),
                ('start', models.DateTimeField(help_text='The start date and time of the booking.')),
                ('guest_count', models.IntegerField(help_text='The number of guests.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='The status of the booking.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the booking.', null=True)),
                ('restaurant', models.ForeignKey(help_text='The restaurant this booking belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('table', models.ForeignKey(help_text='The table reserved for this booking.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
        ),
    ]
