# Generated by Django 3.2.25 on 2024-06-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20240610_0700'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='default_duration',
            field=models.ForeignKey(help_text='The default duration for this restaurant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurant.restaurant'),
        ),
    ]
