# Generated by Django 3.2.25 on 2024-06-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20240603_0906'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(help_text='The number of guests.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(help_text='The name of the guest.', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(help_text='The phone number of the guest.', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for the booking.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this booking belongs to.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(help_text='The start date and time of the booking.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The status of the booking.', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(help_text='The table reserved for this booking.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
        ),
        migrations.DeleteModel(
            name='BookingPeriod',
        ),
    ]
