# Generated by Django 3.2.25 on 2024-06-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_default_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='default_duration',
        ),
    ]
