# Generated by Django 3.2.25 on 2024-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_default_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(blank=True, help_text='The end date and time of the booking.', null=True),
        ),
    ]
