name: Integration Test

on:
  pull_request:
    branches: [ "prod" ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build and run Docker Compose
        run: |
          docker compose -f docker-compose.full.yml up -d --build
        continue-on-error: false
      
      #- name: Run integration tests
      #  run: |
      #    docker compose -f docker-compose.full.yml exec backend npm run test:integration
      #  continue-on-error: false

      - name: cleanup
        run: |
          docker compose -f docker-compose.full.yml down
        continue-on-error: true
      

