name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "prod" ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build and run Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up -d --build
        continue-on-error: false
      
      - name: Run user integration tests
        id: user-tests
        run: |
          docker compose -f docker-compose.test.yml exec web "python manage.py test user" > user_test_output.log
        continue-on-error: false

      - name: Run restaurant integration tests
        id: restaurant-tests
        run: |
          docker compose -f docker-compose.test.yml exec web "python manage.py test restaurant" > restaurant_test_output.log
        continue-on-error: false

      - name: Run booking integration tests
        id: booking-tests
        run: |
          docker compose -f docker-compose.test.yml exec web "python manage.py test booking" > booking_test_output.log
        continue-on-error: false

      - name: Display user test log
        if: always()
        run: cat user_test_output.log

      - name: Display restaurant test log
        if: always()
        run: cat restaurant_test_output.log

      - name: Display booking test log
        if: always()
        run: cat booking_test_output.log

      - name: cleanup
        run: |
          docker compose -f docker-compose.test.yml down
        continue-on-error: true

      - name: Print test outcomes
        run: |
          echo "User tests: ${{ steps['user-tests'].outcome }}"
          echo "Restaurant tests: ${{ steps['restaurant-tests'].outcome }}"
          echo "Booking tests: ${{ steps['booking-tests'].outcome }}"
