name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "prod" ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build and run Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up -d --build
        continue-on-error: false
      
      - name: Run unit tests: user
        run: |
          docker compose -f docker-compose.test.yml exec web test user
        continue-on-error: false

      - name: Run unit tests: restaurant
        run: |
          docker compose -f docker-compose.test.yml exec web test restaurant
        continue-on-error: false

      - name_ run unit tests: booking
        run: |
          docker compose -f docker-compose.test.yml exec web test booking
        continue-on-error: false

      - name: cleanup
        run: |
          docker compose -f docker-compose.test.yml down
        continue-on-error: true