name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "prod" ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up -d --build
        continue-on-error: false

      - name: Run user integration tests
        id: user-tests
        run: |
          docker compose -f docker-compose.test.yml exec web  "python manage.py test user"
        continue-on-error: false

      - name: Run restaurant integration tests
        id: restaurant-tests
        run: |
          docker compose -f docker-compose.test.yml exec web sh -c "python manage.py test restaurant"
        continue-on-error: false

      - name: Run booking integration tests
        id: booking-tests
        run: |
          docker compose -f docker-compose.test.yml exec web sh -c "python manage.py test booking"
        continue-on-error: false

      - name: Cleanup
        run: |
          docker compose -f docker-compose.test.yml down
        continue-on-error: true

      - name: Print test outcomes
        run: |
          echo "User tests: ${{ steps['user-tests'].outcome }}"
          echo "Restaurant tests: ${{ steps['restaurant-tests'].outcome }}"
          echo "Booking tests: ${{ steps['booking-tests'].outcome }}"
